Complete request and response parsing for Route service
daniel-j-h/libosrmc pull request #18
Opened 2020-04-16 15:36 UTC by babu-shanmugam

Modified the osrmc_route in the library to accept a python dictionary object
which eases the usage of the route service from the python binding.

Also added a C++ class to parse the json return value to python dictionary so
that it is easy use in the python binding.

Tested against py2 as well py3

2020-04-16 16:41 UTC, daniel-j-h commented on bindings/osrmcpy.py
> +        return lib.osrmc_error_message(self).decode('latin1')
Why is this needed?

2020-04-16 16:43 UTC, daniel-j-h requested changes

2020-04-16 16:43 UTC, daniel-j-h commented on bindings/osrmcpy.py
> +lib.osrmc_route.argtypes = [c.c_void_p, c.py_object, c.c_void_p]
I don't understand why we are passing a py_object to the C libosrmc library here. The C libosrmc library should not have a dependency on Python; it should be ABI and API stable and free-standing as much as possible.

For example when we use libosrmc from Haskell, how would we pass a py_object to the osrmc_route function?

2020-04-16 16:44 UTC, daniel-j-h commented
Making libosrmc depend on Python is not a way I want us to go.

libosrmc can and is used in other languages, for example from Rust, Haskell. There is no need to depend on Python when using libosrmc from these languages.

2020-04-17 03:59 UTC, babu-shanmugam commented
I understand Daniel. Thanks for your time.

2020-04-17 03:59 UTC, closed without merging